from typing import List, Dict, Optional, TypedDict
from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    """
    State for the legal intake assistant agent.
    """
    # Conversation history (messages between user and AI)
    messages: List[BaseMessage]
    
    # Current questions to ask the user
    current_questions: List[str]
    
    # Whether the session is complete
    is_complete: bool
    
    # Final description generated by the agent
    final_description: Optional[str]
    
    # Answers collected so far
    answers_so_far: Dict[str, str]
    
    # Number of iterations (safety measure to prevent infinite loops)
    iteration_count: int
    
    # Initial description provided by user
    initial_description: str